/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* configure the pins and initialize the registers */
void USART_0_initialization(void)
{

	// Set pin direction to input
	PA5_set_dir(PORT_DIR_IN);

	PA5_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART00_bm;

	// Set pin direction to output

	PA4_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PA4_set_dir(PORT_DIR_OUT);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART00_bm;

	USART_0_init();
}

/* configure the pins and initialize the registers */
void USART_1_initialization(void)
{

	// Set pin direction to input
	PB1_set_dir(PORT_DIR_IN);

	PB1_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	PB0_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PB0_set_dir(PORT_DIR_OUT);

	USART_1_init();
}

/* configure pins and initialize registers */
void I2C_0_initialization(void)
{

	PB3_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PB3_set_dir(
	    // <y> Pin direction
	    // <id> pad_dir
	    // <PORT_DIR_OFF"> Off
	    // <PORT_DIR_IN"> In
	    // <PORT_DIR_OUT"> Out
	    PORT_DIR_OUT);

	PB3_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	PB3_set_inverted(
	    // <y> Invert I/O on pin
	    // <id> pad_invert
	    // <false"> Not inverted
	    // <true"> Inverted
	    false);

	PB3_set_isc(
	    // <y> Pin Input/Sense Configuration
	    // <id> pad_isc
	    // <PORT_ISC_INTDISABLE_gc"> Interrupt disabled but input buffer enabled
	    // <PORT_ISC_BOTHEDGES_gc"> Sense Both Edges
	    // <PORT_ISC_RISING_gc"> Sense Rising Edge
	    // <PORT_ISC_FALLING_gc"> Sense Falling Edge
	    // <PORT_ISC_INPUT_DISABLE_gc"> Digital Input Buffer disabled
	    // <PORT_ISC_LEVEL_gc"> Sense low Level
	    PORT_ISC_INTDISABLE_gc);

	/* set the alternate pin mux */

	PORTMUX.TWIROUTEA |= PORTMUX_TWI11_bm;

	PB2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PB2_set_dir(
	    // <y> Pin direction
	    // <id> pad_dir
	    // <PORT_DIR_OFF"> Off
	    // <PORT_DIR_IN"> In
	    // <PORT_DIR_OUT"> Out
	    PORT_DIR_OUT);

	PB2_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	PB2_set_inverted(
	    // <y> Invert I/O on pin
	    // <id> pad_invert
	    // <false"> Not inverted
	    // <true"> Inverted
	    false);

	PB2_set_isc(
	    // <y> Pin Input/Sense Configuration
	    // <id> pad_isc
	    // <PORT_ISC_INTDISABLE_gc"> Interrupt disabled but input buffer enabled
	    // <PORT_ISC_BOTHEDGES_gc"> Sense Both Edges
	    // <PORT_ISC_RISING_gc"> Sense Rising Edge
	    // <PORT_ISC_FALLING_gc"> Sense Falling Edge
	    // <PORT_ISC_INPUT_DISABLE_gc"> Digital Input Buffer disabled
	    // <PORT_ISC_LEVEL_gc"> Sense low Level
	    PORT_ISC_INTDISABLE_gc);

	/* set the alternate pin mux */

	PORTMUX.TWIROUTEA |= PORTMUX_TWI11_bm;

	I2C_0_init();
}

void TIMER_0_initialization(void)
{

	TIMER_0_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PA0 */

	// Set pin direction to input
	DIP0_set_dir(PORT_DIR_IN);

	DIP0_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_UP);

	/* PORT setting on PA1 */

	// Set pin direction to input
	DIP1_set_dir(PORT_DIR_IN);

	DIP1_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_UP);

	/* PORT setting on PA2 */

	// Set pin direction to input
	DIP2_set_dir(PORT_DIR_IN);

	DIP2_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_UP);

	/* PORT setting on PA3 */

	// Set pin direction to input
	DIP3_set_dir(PORT_DIR_IN);

	DIP3_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_UP);

	/* PORT setting on PA6 */

	// Set pin direction to output

	R8_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R8_set_dir(PORT_DIR_OUT);

	/* PORT setting on PA7 */

	// Set pin direction to output

	status_led_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	status_led_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB4 */

	// Set pin direction to output

	W1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB5 */

	// Set pin direction to output

	B1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB6 */

	// Set pin direction to output

	G1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PB7 */

	// Set pin direction to output

	R1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC0 */

	// Set pin direction to output

	W2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W2_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC1 */

	// Set pin direction to output

	B2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B2_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC2 */

	// Set pin direction to output

	G2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G2_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC3 */

	// Set pin direction to output

	R2_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R2_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC4 */

	// Set pin direction to output

	W3_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W3_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC5 */

	// Set pin direction to output

	B3_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B3_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC6 */

	// Set pin direction to output

	G3_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G3_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC7 */

	// Set pin direction to output

	R3_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R3_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD0 */

	// Set pin direction to output

	W4_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W4_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD1 */

	// Set pin direction to output

	B4_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B4_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD2 */

	/* PORT setting on PD3 */

	// Set pin direction to output

	R4_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R4_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD4 */

	// Set pin direction to output

	W5_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W5_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD5 */

	// Set pin direction to output

	B5_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B5_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD6 */

	// Set pin direction to output

	G5_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G5_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD7 */

	// Set pin direction to output

	R5_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R5_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE0 */

	// Set pin direction to output

	W6_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W6_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE1 */

	// Set pin direction to output

	B6_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B6_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE2 */

	// Set pin direction to output

	G6_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G6_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE3 */

	// Set pin direction to output

	R6_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R6_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE4 */

	// Set pin direction to output

	W7_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W7_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE5 */

	// Set pin direction to output

	B7_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B7_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE6 */

	// Set pin direction to output

	G7_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G7_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE7 */

	// Set pin direction to output

	R7_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R7_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF0 */

	// Set pin direction to output

	W8_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W8_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF1 */

	// Set pin direction to output

	B8_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B8_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF2 */

	// Set pin direction to output

	G8_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G8_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG0 */

	// Set pin direction to output

	W9_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W9_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG1 */

	// Set pin direction to output

	B9_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B9_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG2 */

	// Set pin direction to output

	G9_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G9_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG3 */

	// Set pin direction to output

	R9_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R9_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG4 */

	// Set pin direction to output

	W10_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	W10_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG5 */

	// Set pin direction to output

	B10_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	B10_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG6 */

	// Set pin direction to output

	G10_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	G10_set_dir(PORT_DIR_OUT);

	/* PORT setting on PG7 */

	// Set pin direction to output

	R10_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	R10_set_dir(PORT_DIR_OUT);

	CLKCTRL_init();

	USART_0_initialization();

	USART_1_initialization();

	SLPCTRL_init();

	CPUINT_init();

	I2C_0_initialization();

	TIMER_0_initialization();

	BOD_init();
	
}
